site_name: My Docs

theme:
    name: material

nav:
    - Home: 'index.md'
    - 'Install': 'install.md'
    - 'Use Cases': 'use_cases.md'
    - 'Key Concepts': 'key_concepts.md'
    - 'Commom Issues': 'commom_issues'

markdown_extensions:
    - admonition